### ISSUE TITLE
Timeout triggers for websocket subscriptions aswell

### ISSUE THREAD

**Issue by schavaLogi** [drcallaway/apollo-link-timeout#1]
timeout triggers for WebSocket subscriptions also. would like to apply only for mutation and query only.
is there any option to customize based on operation

**Comment by drcallaway** [comment]
@schavaLogi Thanks for pointing that out! There isn't currently an option to restrict the timeout to query and mutation operations only but I'll work on a solution to address this issue. Perhaps just excluding subscriptions would be the simplest approach.

**Comment by drcallaway** [comment]
@schavaLogi I've addressed your issue with subscriptions with this PR: https://github.com/drcallaway/apollo-link-timeout/pull/4
Basically, we'll just ignore timeouts for subscription requests. What do you think?

**Comment by schavaLogi** [comment]
Yes I think this is a good approach
