### ISSUE TITLE
Add statusCode property to TimeoutError

### ISSUE THREAD

**Issue by alfonmga** [drcallaway/apollo-link-timeout#14]
`TimeoutError` error should contains a `408` code as `statusCode` property.

This would make easier to handle timeout errors.  E.g:
```javascript
if (networkError.statusCode === 408) { … }
```

Otherwise we are only getting an error message `Timeout exceeded`. Handling errors by error message is a mess IMO.

**Comment by drcallaway** [comment]
Good idea. Added in this commit: 877e07da223f840f73bff91935e738f8d94e8184
