### ISSUE TITLE
Error while SSR 

### ISSUE THREAD

**Issue by standy** [drcallaway/apollo-link-timeout#15]
Hello, I was using this lib for SSR, and latest version started to fail

Stack trace pretty obvious:
```
ReferenceError: window is not defined
    at ...\node_modules\apollo-link-timeout\src\timeoutLink.ts:65:7
```

**Comment by drcallaway** [comment]
Fixed by https://github.com/drcallaway/apollo-link-timeout/commit/17347a258529aa662ccdc08be43b006cb8a18008
