### ISSUE TITLE
Incompatible with Apollo Client 3

### ISSUE THREAD

**Issue by akornato** [drcallaway/apollo-link-timeout#36]
`onError, setOnError` are missing when trying to use with `@apollo/client` `3.2.0-rc.0`:

<img width="804" alt="Screenshot 2020-09-13 at 08 03 43" src="https://user-images.githubusercontent.com/14935179/93011596-c7d95f80-f597-11ea-8eef-3f3ff89b8852.png">

**Comment by guiccbr** [comment]
The newest release is compatible: https://www.npmjs.com/package/apollo-link-timeout/v/4.0.0
