### ISSUE TITLE
Build es version to support react-native

### ISSUE THREAD

**Issue by christophehurpeau** [drcallaway/apollo-link-timeout#45]
Hey,

it would be grate to have an es version for react-native and also better treeshaking with webpack.
It seems you build with typescript so I don't know how that would work to have multiple targets, but if you want I can look into this and help create a PR

I have this error with react-native:

```
[Thu Jul 08 2021 13:37:09.203]  ERROR    ReferenceError: Can't find variable: client_1
```

And the only reference of `client_1` is apollo-link-timeout. Modifying to `import * as client_1 from '@apollo/client';` in the dist file works.

Thanks

**Comment by christophehurpeau** [comment]
Upgrading to v4 seems to resolve the issue. Sorry for opening an issue without enough investigating ! However, let me know what you think about es version

**Comment by drcallaway** [comment]
Hi @christophehurpeau. This project hasn't been in active development for some time and I'm not looking to add any new features but if you'd like to submit a PR, I'd be happy to review and possibly merge it.
