### ISSUE TITLE
When Operation Timed out the error not received by the initiator as we are unsubscribe before onError

### ISSUE THREAD

**Issue by schavaLogi** [drcallaway/apollo-link-timeout#5]
https://github.com/drcallaway/apollo-link-timeout/blob/c325c77324f3fb737c6cdc1f77e1ce7246fba77d/src/timeoutLink.ts#L65

I think the order should be reversed. first, we need to throw Error and then unsubscribe so that the initiator will be notified

**Comment by drcallaway** [comment]
Thanks @schavaLogi ! Please let me know if you still see a problem.
Fixed by #6.
